const mockPeaks = {
  isRedoEnabled: false,
  isUndoEnabled: true,
  operation: 'addPeak',
  peakTable: [
    {
      area: 0.02043,
      asymmetry: 3.60851,
      efficiency: 102.631,
      halfwidth: 12.2,
      height: 0.00112,
      isMasterPeak: false,
      isNotSeparatedLeft: false,
      isNotSeparatedLeftEnable: false,
      isNotSeparatedRight: false,
      isNotSeparatedRightEnable: false,
      isNotSeparatedWithNum: null,
      isRiderEnable: false,
      isRiderPeak: false,
      leftBoundary: 60.2,
      masterPeakNumber: null,
      peakNumber: 1,
      resolution: 0.883557,
      riderPeakNumbers: [],
      rightBoundary: 153.2,
      time: 73.6,
    },
    {
      area: 0.05462,
      asymmetry: 4.19851,
      efficiency: 4.15824,
      halfwidth: 319.8,
      height: 0.00014,
      isMasterPeak: false,
      isNotSeparatedLeft: false,
      isNotSeparatedLeftEnable: false,
      isNotSeparatedRight: false,
      isNotSeparatedRightEnable: true,
      isNotSeparatedWithNum: null,
      isRiderEnable: false,
      isRiderPeak: false,
      leftBoundary: 157.6,
      masterPeakNumber: null,
      peakNumber: 2,
      resolution: 2.26922,
      riderPeakNumbers: [],
      rightBoundary: 896.4,
      time: 307.8,
    },
    {
      area: 0.05116,
      asymmetry: 1.22213,
      efficiency: 7902.44,
      halfwidth: 23.7,
      height: 0.00195,
      isMasterPeak: false,
      isNotSeparatedLeft: false,
      isNotSeparatedLeftEnable: true,
      isNotSeparatedRight: false,
      isNotSeparatedRightEnable: false,
      isNotSeparatedWithNum: null,
      isRiderEnable: false,
      isRiderPeak: false,
      leftBoundary: 896.8,
      masterPeakNumber: null,
      peakNumber: 3,
      resolution: null,
      riderPeakNumbers: [],
      rightBoundary: 1001.8,
      time: 931.6,
    },
  ],
};

module.exports = {
  mockPeaks,
};
